spring:
  data:
    mongodb:
      uri: mongodb://delivery:delivery@localhost:27017/delivery?authSource=admin
      database: delivery
      auto-index-creation: true
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
#  springdoc:
#    api-docs:
#      path: /api-docs
logging:
  level:
    com:
      delivery:
        trizi:
          trizi: DEBUG

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY:AKIAR63SZWDKEHCW5TPK}
      secret-key: ${SECRET_KEY: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}
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: productss3delivery

