spring:
  data:
    mongodb:
      uri: mongodb://delivery:delivery@localhost:27017/delivery?authSource=admin
      database: delivery
      auto-index-creation: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

logging:
  level:
    com:
      delivery:
        trizi:
          trizi: DEBUG

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY:AKIAR63SZWDKFTC2ZVTQ}
      secret-key: ${SECRET_KEY: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}
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: productss3delivery
