openapi: 3.0.0
info:
  title: Ecommerce
  description: API completa para Ecommerce
  version: V1
  contact:
    name: Yuri Matthewus
    email: yuri_matteus@hotmail.com
    url: https://github.com/iru-Y/Ecommerce-DropShipping-Java
paths:
  /v1/**:
    get:
      summary: Descrição da operação GET
      responses:
        '200':
          description: Sucesso
    post:
      summary: Descrição da operação POST
      responses:
        '201':
          description: Criado com sucesso
